# Generated by Django 4.0.4 on 2022-04-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_show_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='new_field',
        ),
    ]
