# Generated by Django 4.0.4 on 2022-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_show_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
