# Generated by Django 4.0.4 on 2022-04-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('shows', '0005_alter_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.actor'),
        ),
    ]
